// Generated by CoffeeScript 1.3.3
var app, escapeHTML, express, http, io, path, routes, server;

express = require("express");

routes = require('./routes');

http = require('http');

path = require('path');

app = express();

app.configure(function() {
  app.set('port', process.env.PORT || 3000);
  app.set("view engine", "ejs");
  app.use(express.logger('dev'));
  app.use(express.bodyParser());
  app.use(express.methodOverride());
  app.use(app.router);
  return app.use(express["static"](path.join(__dirname, 'public')));
});

/*
  app.set "view options",
    layout: false
*/


app.get('/', routes.index);

server = http.createServer(app);

io = require("socket.io").listen(server);

server.listen(app.get('port'));

/*
app.get "/", (req, res) ->
  res.render "index",
    title : 'SW (node.js+express+socket.io ChatApp)use ejs+coffee'
    desc  : 'SW chat App Test'
    locals:
        port:port  # portは要検証
*/


io.sockets.on("connection", function(client) {
  client.on("message", function(msg) {
    var sanitized;
    sanitized = escapeHTML(msg);
    client.send(sanitized);
    return client.broadcast(sanitized);
  });
  return client.on("disconnect", function() {
    console.log("disconnect");
    return client.broadcast(client.sessionId + ' disconnected');
  });
});

escapeHTML = function(str) {
  return str.replace(/&/g, "&amp;").replace(/"/g, "&quot;").replace(/>/g, "&gt;");
};
